#Famelo:
  #Messaging:
    # redirectAllMessagesTo: foo@bar.com
    # defaultFrom:
    #   mneuhaus@famelo.com: 'Marc Neuhaus'
    # request:
    #   defaultPackage: 'My.Package'
    #   defaultSubpackage: 'Frontend'
    #   defaultController: 'Standard'

# TYPO3:
#   SwiftMailer:
#     transport:
#       type: 'Swift_SmtpTransport'
#       options:
#         host: 'mail.foo.com'
#         username: 'foo'
#         password: 'bar'